### ISSUE TITLE
Usernames are forced lowercase

### ISSUE THREAD

**Issue by Semisol** [ScratchVerifier/ScratchOAuth2#57]
Usernames are always returned lowercase. They should instead return the result from the Scratch API as properly capitalized. If this makes DB problems just use another column.

**Comment by micahlt** [comment]
@Semisol @Kenny2github is there any plan to continue supporting this?  I'm getting ready to launch Modchat v2, and at the moment ScratchOAuth2 has multiple issues (this being one of them), including the fact that session times are way too short.  If this can't be fixed or at least promised a future update I will be moving away from SOA2 as the auth solution for Modchat.

**Comment by Kenny2github** [comment]
@micahlt You haven't opened GitHub issues for any of your "multiple issues". If you want them resolved, you have to report them. Additionally, there was no indication that it was actually causing problems for anyone until your comment.

I will be working on this sometime this week (hopefully). Please open GitHub issues for the other problems you've encountered, and make constructive suggestions for their improvement.

**Comment by micahlt** [comment]
@Kenny2github Apologies if my message sounded harsh - I just need to ensure that SOA2 isn't a dead project before I use it to launch a multi-user webapp.  I was told by @Semisol that you were aware of the session length issues and were going to fix them if you ever came back to the project.  I'll file some GitHub issues and let you look over them.

**Comment by Kenny2github** [comment]
@micahlt Understood, thanks!
