### ISSUE TITLE
Fatal Exception type "Error"

### ISSUE THREAD

**Issue by Shonagon-Sei** [ScratchVerifier/ScratchOAuth2#65]
I have been using this oauth2 for quite a while (years even), but now the website responds with 
`[ZRTzPjvXpW-QAf4xMkuzKwAAkRE] 2023-09-28 03:30:06: Fatal exception of type "Error"` 
for a few weeks now

**Comment by Kenny2github** [comment]
Sanity check: The Wikis have been intermittently down as of late. Is this still happening?
